/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/credit-note/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Credit Note
         * @description Generate a CreditNote XML document.
         *
         *     The `validate` query parameter controls SUNAT validation and defaults to `true`.
         *
         *     Returns:
         *         200: `{"xml": "..."}` with the generated XML.
         *         422: Validation failed or the request body is invalid.
         */
        post: operations["create_credit_note_api_v1_credit_note_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/debit-note/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Debit Note
         * @description Generate a DebitNote XML document.
         *
         *     The `validate` query parameter controls SUNAT validation and defaults to `true`.
         *
         *     Returns:
         *         200: `{"xml": "..."}` with the generated XML.
         *         422: Validation failed or the request body is invalid.
         */
        post: operations["create_debit_note_api_v1_debit_note_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoice/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Invoice
         * @description Generate an Invoice XML document.
         *
         *     The `validate` query parameter controls SUNAT validation and defaults to `true`.
         *
         *     Returns:
         *         200: `{"xml": "..."}` with the generated XML.
         *         422: Validation failed or the request body is invalid.
         */
        post: operations["create_invoice_api_v1_invoice_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/perception/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Perception
         * @description Generate a Perception XML document.
         *
         *     The `validate` query parameter controls SUNAT validation and defaults to `true`.
         *
         *     Returns:
         *         200: `{"xml": "..."}` with the generated XML.
         *         422: Validation failed or the request body is invalid.
         */
        post: operations["create_perception_api_v1_perception_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/retention/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Retention
         * @description Generate a Retention XML document.
         *
         *     The `validate` query parameter controls SUNAT validation and defaults to `true`.
         *
         *     Returns:
         *         200: `{"xml": "..."}` with the generated XML.
         *         422: Validation failed or the request body is invalid.
         */
        post: operations["create_retention_api_v1_retention_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign Xml
         * @description Sign an arbitrary UBL XML document with a PEM certificate/key pair or a PFX/P12 container.
         *
         *     Required body fields (choose one credential mode):
         *         * PEM mode: `cert_pem` and `key_pem`.
         *         * PFX/P12 mode: `pfx_base64` (standard base64 of the file) and `pfx_password`.
         *
         *     Optional body fields:
         *         * `xml`: The XML string to sign.
         *         * `signature_id`: The signature ID (defaults to `SignSUNAT`).
         *
         *     Returns:
         *         200: `{"signed_xml": "..."}` with the signed XML.
         */
        post: operations["sign_xml_api_v1_sign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summary-documents/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Summary Documents
         * @description Generate a SummaryDocuments XML document.
         *
         *     The `validate` query parameter controls SUNAT validation and defaults to `true`.
         *
         *     Returns:
         *         200: `{"xml": "..."}` with the generated XML.
         *         422: Validation failed or the request body is invalid.
         */
        post: operations["create_summary_documents_api_v1_summary_documents_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Version
         * @description Return the current API version.
         *
         *     Returns:
         *         200: `{"version": "..."}` with the current API version.
         */
        get: operations["get_version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/voided-documents/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Voided Documents
         * @description Generate a VoidedDocuments XML document.
         *
         *     The `validate` query parameter controls SUNAT validation and defaults to `true`.
         *
         *     Returns:
         *         200: `{"xml": "..."}` with the generated XML.
         *         422: Validation failed or the request body is invalid.
         */
        post: operations["create_voided_documents_api_v1_voided_documents_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Address
         * @description Dirección según esquema UBL 2.1 de SUNAT.
         */
        Address: {
            /**
             * Codigopais
             * @default PE
             */
            codigoPais: string;
            /** Departamento */
            departamento?: string | null;
            /** Direccion */
            direccion?: string | null;
            /** Distrito */
            distrito?: string | null;
            /** Provincia */
            provincia?: string | null;
            /** Ubigeo */
            ubigeo?: string | null;
            /** Urbanizacion */
            urbanizacion?: string | null;
        };
        /**
         * Cliente
         * @description Datos del adquirente o usuario.
         *
         *     RS N° 300-2014/SUNAT, Anexo 1:
         *     - Tipo de documento: Catálogo N.° 06
         *     - Número de documento: según tipo
         */
        Cliente: {
            /** Nombre */
            nombre: string;
            /** Numerodocumentoidentidad */
            numeroDocumentoIdentidad: string;
            /** Tipodocumentoidentidad */
            tipoDocumentoIdentidad: string;
        };
        /**
         * Comprobante
         * @description Comprobante dentro del resumen diario.
         */
        Comprobante: {
            cliente: components["schemas"]["Cliente"];
            comprobanteAfectado?: components["schemas"]["openubl__models__summary__ComprobanteAfectado"] | null;
            impuestos: components["schemas"]["ComprobanteImpuestos"];
            /** Serienumero */
            serieNumero: string;
            /** Tipocomprobante */
            tipoComprobante: string;
            valorVenta: components["schemas"]["ComprobanteValorVenta"];
        };
        /**
         * ComprobanteImpuestos
         * @description Impuestos del comprobante resumido.
         */
        ComprobanteImpuestos: {
            /** Icb */
            icb?: number | string | null;
            /** Igv */
            igv: number | string;
        };
        /**
         * ComprobanteValorVenta
         * @description Valores de venta del comprobante resumido.
         */
        ComprobanteValorVenta: {
            /** Exonerado */
            exonerado?: number | string | null;
            /** Gravado */
            gravado?: number | string | null;
            /** Importetotal */
            importeTotal: number | string;
            /** Inafecto */
            inafecto?: number | string | null;
        };
        /**
         * CreditNote
         * @description Nota de Crédito Electrónica - Tipo 07.
         *
         *     RS N° 300-2014/SUNAT, Anexo 1:
         *     - Serie: debe iniciar con B/C o F/E según tipo de documento afectado
         *     - Debe referenciar el comprobante afectado
         */
        CreditNote: {
            cliente: components["schemas"]["Cliente"];
            /** Comprobanteafectadoserienumero */
            comprobanteAfectadoSerieNumero: string;
            /** Detalles */
            detalles: components["schemas"]["DocumentoVentaDetalle"][];
            /** Fechaemision */
            fechaEmision?: string | null;
            /** Igvtotal */
            igvTotal?: number | string | null;
            /** Importetotal */
            importeTotal?: number | string | null;
            /**
             * Moneda
             * @default PEN
             */
            moneda: string;
            /** Numero */
            numero: number;
            proveedor: components["schemas"]["Proveedor"];
            /**
             * Serie
             * @description Serie de nota de crédito
             */
            serie: string;
            /** Sustentodescripcion */
            sustentoDescripcion: string;
            /** Valorventatotal */
            valorVentaTotal?: number | string | null;
        };
        /**
         * DebitNote
         * @description Nota de Débito Electrónica - Tipo 08.
         *
         *     RS N° 300-2014/SUNAT, Anexo 1:
         *     - Serie: debe iniciar con B/C o F/E según tipo de documento afectado
         *     - Debe referenciar el comprobante afectado
         */
        DebitNote: {
            cliente: components["schemas"]["Cliente"];
            /** Comprobanteafectadoserienumero */
            comprobanteAfectadoSerieNumero: string;
            /** Detalles */
            detalles: components["schemas"]["DocumentoVentaDetalle"][];
            /** Fechaemision */
            fechaEmision?: string | null;
            /** Igvtotal */
            igvTotal?: number | string | null;
            /** Importetotal */
            importeTotal?: number | string | null;
            /**
             * Moneda
             * @default PEN
             */
            moneda: string;
            /** Numero */
            numero: number;
            proveedor: components["schemas"]["Proveedor"];
            /**
             * Serie
             * @description Serie de nota de débito
             */
            serie: string;
            /** Sustentodescripcion */
            sustentoDescripcion: string;
            /** Valorventatotal */
            valorVentaTotal?: number | string | null;
        };
        /**
         * DocumentoVentaDetalle
         * @description Línea de detalle de un documento de venta.
         *
         *     RS N° 300-2014/SUNAT, Anexo 1:
         *     - Descripción del bien o servicio
         *     - Cantidad y unidad de medida (Catálogo N.° 03)
         *     - Valor unitario (sin IGV)
         *     - Tipo de afectación del IGV (Catálogo N.° 07)
         */
        DocumentoVentaDetalle: {
            /** Cantidad */
            cantidad: number | string;
            /** Descripcion */
            descripcion: string;
            /** Igv */
            igv?: number | string | null;
            /** Precio */
            precio: number | string;
            /** Precioventa */
            precioVenta?: number | string | null;
            /**
             * Tipoafectacionigv
             * @default 10
             */
            tipoAfectacionIGV: string;
            /**
             * Unidadmedida
             * @default NIU
             */
            unidadMedida: string;
            /** Valorventa */
            valorVenta?: number | string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Invoice
         * @description Factura Electrónica - Tipo 01.
         *
         *     RS N° 300-2014/SUNAT, Anexo 1:
         *     - Serie: debe iniciar con F (factura) o B (boleta)
         *     - Número: correlativo
         *     - Tipo de operación: Catálogo N.° 51, default 0101 (Venta interna)
         */
        Invoice: {
            cliente: components["schemas"]["Cliente"];
            /** Detalles */
            detalles: components["schemas"]["DocumentoVentaDetalle"][];
            /** Fechaemision */
            fechaEmision?: string | null;
            /** Igvtotal */
            igvTotal?: number | string | null;
            /** Importetotal */
            importeTotal?: number | string | null;
            /**
             * Moneda
             * @default PEN
             */
            moneda: string;
            /** Numero */
            numero: number;
            proveedor: components["schemas"]["Proveedor"];
            /**
             * Serie
             * @description Serie de factura (F001) o boleta (B001)
             */
            serie: string;
            /**
             * Tipooperacion
             * @default 0101
             */
            tipoOperacion: string;
            /** Valorventatotal */
            valorVentaTotal?: number | string | null;
        };
        /**
         * PercepcionRetencionOperacion
         * @description Operación de percepción.
         */
        PercepcionRetencionOperacion: {
            comprobante: components["schemas"]["openubl__models__perception__ComprobanteAfectado"];
            /**
             * Fechaoperacion
             * Format: date
             */
            fechaOperacion: string;
            /** Importeoperacion */
            importeOperacion: number | string;
            /** Numerooperacion */
            numeroOperacion: number;
        };
        /**
         * Perception
         * @description Comprobante de Percepción Electrónico - Tipo 40.
         *
         *     RS N° 274-2015/SUNAT, Anexo 1:
         *     - Serie: P### (P001, P002, etc.)
         *     - Régimen: Catálogo N.° 22
         */
        Perception: {
            cliente: components["schemas"]["Cliente"];
            /**
             * Fechaemision
             * Format: date
             */
            fechaEmision: string;
            /** Importetotalcobrado */
            importeTotalCobrado: number | string;
            /** Importetotalpercibido */
            importeTotalPercibido: number | string;
            /** Numero */
            numero: number;
            /** Operaciones */
            operaciones: components["schemas"]["PercepcionRetencionOperacion"][];
            proveedor: components["schemas"]["Proveedor"];
            /**
             * Serie
             * @description Serie de percepción (P###)
             */
            serie: string;
            /** Tiporegimen */
            tipoRegimen: string;
            /** Tiporegimenporcentaje */
            tipoRegimenPorcentaje: number | string;
        };
        /**
         * Proveedor
         * @description Datos del emisor del comprobante.
         *
         *     RS N° 300-2014/SUNAT, Anexo 1:
         *     - RUC del emisor: 11 dígitos numéricos (Catálogo N.° 06, valor 6)
         *     - Razón social: obligatoria
         */
        Proveedor: {
            address?: components["schemas"]["Address"] | null;
            /** Nombrecomercial */
            nombreComercial?: string | null;
            /** Razonsocial */
            razonSocial: string;
            /**
             * Ruc
             * @description RUC del emisor - 11 dígitos numéricos
             */
            ruc: string;
        };
        /**
         * Retention
         * @description Comprobante de Retención Electrónico - Tipo 20.
         *
         *     RS N° 274-2015/SUNAT, Anexo 1:
         *     - Serie: R### (R001, R002, etc.)
         *     - Régimen: Catálogo N.° 23
         */
        Retention: {
            /** Importetotalpagado */
            importeTotalPagado: number | string;
            /** Importetotalretenido */
            importeTotalRetenido: number | string;
            /** Operaciones */
            operaciones: components["schemas"]["PercepcionRetencionOperacion"][];
            /**
             * Serie
             * @description Serie de retención (R###)
             */
            serie: string;
            /** Tiporegimen */
            tipoRegimen: string;
            /** Tiporegimenporcentaje */
            tipoRegimenPorcentaje: number | string;
        };
        /**
         * SummaryDocuments
         * @description Resumen Diario - RC.
         *
         *     RS N° 300-2014/SUNAT, Anexo 1:
         *     - Identificador: RC-YYYYMMDD-NNNN
         *     - Fecha de emisión de los comprobantes resumidos
         */
        SummaryDocuments: {
            /** Comprobantes */
            comprobantes: components["schemas"]["SummaryDocumentsItem"][];
            /**
             * Fechaemisioncomprobantes
             * Format: date
             */
            fechaEmisionComprobantes: string;
            /** Numero */
            numero: number;
            proveedor: components["schemas"]["Proveedor"];
        };
        /**
         * SummaryDocumentsItem
         * @description Item del resumen diario.
         *
         *     RS N° 300-2014/SUNAT, Anexo 1:
         *     - Tipo de operación: Catálogo N.° 19 (ADICIONAR, MODIFICAR, ANULADO)
         */
        SummaryDocumentsItem: {
            comprobante: components["schemas"]["Comprobante"];
            /** Tipooperacion */
            tipoOperacion: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VoidedDocuments
         * @description Comunicación de Baja - RA.
         *
         *     RS N° 300-2014/SUNAT, Anexo 1:
         *     - Identificador: RA-YYYYMMDD-NNNN
         *     - Fecha de emisión de los comprobantes que se dan de baja
         */
        VoidedDocuments: {
            /** Comprobantes */
            comprobantes: components["schemas"]["VoidedDocumentsItem"][];
            /** Fechaemision */
            fechaEmision?: string | null;
            /**
             * Fechaemisioncomprobantes
             * Format: date
             */
            fechaEmisionComprobantes: string;
            /** Numero */
            numero: number;
            proveedor: components["schemas"]["Proveedor"];
        };
        /**
         * VoidedDocumentsItem
         * @description Item de comunicación de baja.
         *
         *     RS N° 300-2014/SUNAT, Anexo 1:
         *     - Tipo de comprobante: Catálogo N.° 01
         *     - Serie y número del comprobante a dar de baja
         */
        VoidedDocumentsItem: {
            /** Descripcionsustento */
            descripcionSustento: string;
            /** Numero */
            numero: number;
            /** Serie */
            serie: string;
            /** Tipocomprobante */
            tipoComprobante: string;
        };
        /**
         * ComprobanteAfectado
         * @description Comprobante afectado por la percepción.
         */
        openubl__models__perception__ComprobanteAfectado: {
            /**
             * Fechaemision
             * Format: date
             */
            fechaEmision: string;
            /** Importetotal */
            importeTotal: number | string;
            /** Moneda */
            moneda: string;
            /** Serienumero */
            serieNumero: string;
            /** Tipocomprobante */
            tipoComprobante: string;
        };
        /**
         * ComprobanteAfectado
         * @description Comprobante afectado para notas.
         */
        openubl__models__summary__ComprobanteAfectado: {
            /**
             * Fechaemision
             * Format: date
             */
            fechaEmision: string;
            /** Importetotal */
            importeTotal: number | string;
            /** Moneda */
            moneda: string;
            /** Serienumero */
            serieNumero: string;
            /** Tipocomprobante */
            tipoComprobante: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_credit_note_api_v1_credit_note_create_post: {
        parameters: {
            query?: {
                validate?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreditNote"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_debit_note_api_v1_debit_note_create_post: {
        parameters: {
            query?: {
                validate?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebitNote"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invoice_api_v1_invoice_create_post: {
        parameters: {
            query?: {
                validate?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Invoice"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_perception_api_v1_perception_create_post: {
        parameters: {
            query?: {
                validate?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Perception"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_retention_api_v1_retention_create_post: {
        parameters: {
            query?: {
                validate?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Retention"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_xml_api_v1_sign_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_summary_documents_api_v1_summary_documents_create_post: {
        parameters: {
            query?: {
                validate?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummaryDocuments"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_voided_documents_api_v1_voided_documents_create_post: {
        parameters: {
            query?: {
                validate?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoidedDocuments"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
