// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { CreateCreditNoteData, CreateCreditNoteErrors, CreateCreditNoteResponses, CreateDebitNoteData, CreateDebitNoteErrors, CreateDebitNoteResponses, CreateInvoiceData, CreateInvoiceErrors, CreateInvoiceResponses, CreatePerceptionData, CreatePerceptionErrors, CreatePerceptionResponses, CreateRetentionData, CreateRetentionErrors, CreateRetentionResponses, CreateSummaryDocumentsData, CreateSummaryDocumentsErrors, CreateSummaryDocumentsResponses, CreateVoidedDocumentsData, CreateVoidedDocumentsErrors, CreateVoidedDocumentsResponses, GetVersionData, GetVersionResponses, SignXmlData, SignXmlErrors, SignXmlResponses } from './types.gen.js';
import { zCreateCreditNoteBody, zCreateCreditNoteQuery, zCreateCreditNoteResponse, zCreateDebitNoteBody, zCreateDebitNoteQuery, zCreateDebitNoteResponse, zCreateInvoiceBody, zCreateInvoiceQuery, zCreateInvoiceResponse, zCreatePerceptionBody, zCreatePerceptionQuery, zCreatePerceptionResponse, zCreateRetentionBody, zCreateRetentionQuery, zCreateRetentionResponse, zCreateSummaryDocumentsBody, zCreateSummaryDocumentsQuery, zCreateSummaryDocumentsResponse, zCreateVoidedDocumentsBody, zCreateVoidedDocumentsQuery, zCreateVoidedDocumentsResponse, zSignXmlBody, zSignXmlResponse } from './zod.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Create Credit Note
 *
 * Generate a CreditNote XML document.
 *
 * The `validate` query parameter controls SUNAT validation and defaults to `true`.
 *
 * Returns:
 * 200: `{"xml": "..."}` with the generated XML.
 * 422: Validation failed or the request body is invalid.
 */
export const createCreditNote = <ThrowOnError extends boolean = false>(options: Options<CreateCreditNoteData, ThrowOnError>): RequestResult<CreateCreditNoteResponses, CreateCreditNoteErrors, ThrowOnError> => (options.client ?? client).post<CreateCreditNoteResponses, CreateCreditNoteErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zCreateCreditNoteBody,
        path: z.never().optional(),
        query: zCreateCreditNoteQuery.optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zCreateCreditNoteResponse.parseAsync(data),
    url: '/api/v1/credit-note/create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create Debit Note
 *
 * Generate a DebitNote XML document.
 *
 * The `validate` query parameter controls SUNAT validation and defaults to `true`.
 *
 * Returns:
 * 200: `{"xml": "..."}` with the generated XML.
 * 422: Validation failed or the request body is invalid.
 */
export const createDebitNote = <ThrowOnError extends boolean = false>(options: Options<CreateDebitNoteData, ThrowOnError>): RequestResult<CreateDebitNoteResponses, CreateDebitNoteErrors, ThrowOnError> => (options.client ?? client).post<CreateDebitNoteResponses, CreateDebitNoteErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zCreateDebitNoteBody,
        path: z.never().optional(),
        query: zCreateDebitNoteQuery.optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zCreateDebitNoteResponse.parseAsync(data),
    url: '/api/v1/debit-note/create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create Invoice
 *
 * Generate an Invoice XML document.
 *
 * The `validate` query parameter controls SUNAT validation and defaults to `true`.
 *
 * Returns:
 * 200: `{"xml": "..."}` with the generated XML.
 * 422: Validation failed or the request body is invalid.
 */
export const createInvoice = <ThrowOnError extends boolean = false>(options: Options<CreateInvoiceData, ThrowOnError>): RequestResult<CreateInvoiceResponses, CreateInvoiceErrors, ThrowOnError> => (options.client ?? client).post<CreateInvoiceResponses, CreateInvoiceErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zCreateInvoiceBody,
        path: z.never().optional(),
        query: zCreateInvoiceQuery.optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zCreateInvoiceResponse.parseAsync(data),
    url: '/api/v1/invoice/create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create Perception
 *
 * Generate a Perception XML document.
 *
 * The `validate` query parameter controls SUNAT validation and defaults to `true`.
 *
 * Returns:
 * 200: `{"xml": "..."}` with the generated XML.
 * 422: Validation failed or the request body is invalid.
 */
export const createPerception = <ThrowOnError extends boolean = false>(options: Options<CreatePerceptionData, ThrowOnError>): RequestResult<CreatePerceptionResponses, CreatePerceptionErrors, ThrowOnError> => (options.client ?? client).post<CreatePerceptionResponses, CreatePerceptionErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zCreatePerceptionBody,
        path: z.never().optional(),
        query: zCreatePerceptionQuery.optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zCreatePerceptionResponse.parseAsync(data),
    url: '/api/v1/perception/create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create Retention
 *
 * Generate a Retention XML document.
 *
 * The `validate` query parameter controls SUNAT validation and defaults to `true`.
 *
 * Returns:
 * 200: `{"xml": "..."}` with the generated XML.
 * 422: Validation failed or the request body is invalid.
 */
export const createRetention = <ThrowOnError extends boolean = false>(options: Options<CreateRetentionData, ThrowOnError>): RequestResult<CreateRetentionResponses, CreateRetentionErrors, ThrowOnError> => (options.client ?? client).post<CreateRetentionResponses, CreateRetentionErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zCreateRetentionBody,
        path: z.never().optional(),
        query: zCreateRetentionQuery.optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zCreateRetentionResponse.parseAsync(data),
    url: '/api/v1/retention/create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Sign Xml
 *
 * Sign an arbitrary UBL XML document with a PEM certificate/key pair or a PFX/P12 container.
 *
 * Required body fields (choose one credential mode):
 * * PEM mode: `cert_pem` and `key_pem`.
 * * PFX/P12 mode: `pfx_base64` (standard base64 of the file) and `pfx_password`.
 *
 * Optional body fields:
 * * `xml`: The XML string to sign.
 * * `signature_id`: The signature ID (defaults to `SignSUNAT`).
 *
 * Returns:
 * 200: `{"signed_xml": "..."}` with the signed XML.
 */
export const signXml = <ThrowOnError extends boolean = false>(options: Options<SignXmlData, ThrowOnError>): RequestResult<SignXmlResponses, SignXmlErrors, ThrowOnError> => (options.client ?? client).post<SignXmlResponses, SignXmlErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zSignXmlBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zSignXmlResponse.parseAsync(data),
    url: '/api/v1/sign',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create Summary Documents
 *
 * Generate a SummaryDocuments XML document.
 *
 * The `validate` query parameter controls SUNAT validation and defaults to `true`.
 *
 * Returns:
 * 200: `{"xml": "..."}` with the generated XML.
 * 422: Validation failed or the request body is invalid.
 */
export const createSummaryDocuments = <ThrowOnError extends boolean = false>(options: Options<CreateSummaryDocumentsData, ThrowOnError>): RequestResult<CreateSummaryDocumentsResponses, CreateSummaryDocumentsErrors, ThrowOnError> => (options.client ?? client).post<CreateSummaryDocumentsResponses, CreateSummaryDocumentsErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zCreateSummaryDocumentsBody,
        path: z.never().optional(),
        query: zCreateSummaryDocumentsQuery.optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zCreateSummaryDocumentsResponse.parseAsync(data),
    url: '/api/v1/summary-documents/create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Version
 *
 * Return the current API version.
 *
 * Returns:
 * 200: `{"version": "..."}` with the current API version.
 */
export const getVersion = <ThrowOnError extends boolean = false>(options?: Options<GetVersionData, ThrowOnError>): RequestResult<GetVersionResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetVersionResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/api/v1/version',
    ...options
});

/**
 * Create Voided Documents
 *
 * Generate a VoidedDocuments XML document.
 *
 * The `validate` query parameter controls SUNAT validation and defaults to `true`.
 *
 * Returns:
 * 200: `{"xml": "..."}` with the generated XML.
 * 422: Validation failed or the request body is invalid.
 */
export const createVoidedDocuments = <ThrowOnError extends boolean = false>(options: Options<CreateVoidedDocumentsData, ThrowOnError>): RequestResult<CreateVoidedDocumentsResponses, CreateVoidedDocumentsErrors, ThrowOnError> => (options.client ?? client).post<CreateVoidedDocumentsResponses, CreateVoidedDocumentsErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zCreateVoidedDocumentsBody,
        path: z.never().optional(),
        query: zCreateVoidedDocumentsQuery.optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zCreateVoidedDocumentsResponse.parseAsync(data),
    url: '/api/v1/voided-documents/create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
