// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Address
 *
 * Dirección según esquema UBL 2.1 de SUNAT.
 */
export type Address = {
    /**
     * Codigopais
     */
    codigoPais?: string;
    /**
     * Departamento
     */
    departamento?: string | null;
    /**
     * Direccion
     */
    direccion?: string | null;
    /**
     * Distrito
     */
    distrito?: string | null;
    /**
     * Provincia
     */
    provincia?: string | null;
    /**
     * Ubigeo
     */
    ubigeo?: string | null;
    /**
     * Urbanizacion
     */
    urbanizacion?: string | null;
};

/**
 * Catalog1
 *
 * Tipo de Comprobante - Catálogo N.° 01
 */
export type Catalog1 = '01' | '03' | '07' | '08' | '09' | '20' | '40';

/**
 * Catalog19
 *
 * Tipo de Operación - Resumen Diario - Catálogo N.° 19
 */
export type Catalog19 = '1' | '2' | '3';

/**
 * Catalog2
 *
 * Tipo de Moneda - Catálogo N.° 02
 */
export type Catalog2 = 'PEN' | 'USD' | 'EUR';

/**
 * Catalog22
 *
 * Régimen de Percepción - Catálogo N.° 22
 */
export type Catalog22 = '01' | '02' | '03';

/**
 * Catalog23
 *
 * Régimen de Retención - Catálogo N.° 23
 */
export type Catalog23 = '01' | '02' | '03';

/**
 * Catalog51
 *
 * Tipo de Operación - Catálogo N.° 51
 */
export type Catalog51 = '0101' | '0102' | '0103' | '0104' | '0105' | '0106' | '0107' | '0108' | '0110' | '0200' | '0201' | '0202' | '0203' | '0204' | '0205' | '0206' | '0207';

/**
 * Catalog6
 *
 * Tipo de Documento de Identidad - Catálogo N.° 06
 */
export type Catalog6 = '0' | '1' | '4' | '6' | '7';

/**
 * Catalog7
 *
 * Tipo de Afectación del IGV - Catálogo N.° 07
 */
export type Catalog7 = '10' | '20' | '30';

/**
 * Cliente
 *
 * Datos del adquirente o usuario.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Tipo de documento: Catálogo N.° 06
 * - Número de documento: según tipo
 */
export type Cliente = {
    /**
     * Nombre
     */
    nombre: string;
    /**
     * Numerodocumentoidentidad
     */
    numeroDocumentoIdentidad: string;
    tipoDocumentoIdentidad: Catalog6;
};

/**
 * Comprobante
 *
 * Comprobante dentro del resumen diario.
 */
export type Comprobante = {
    cliente: Cliente;
    comprobanteAfectado?: OpenublModelsSummaryComprobanteAfectado | null;
    impuestos: ComprobanteImpuestos;
    /**
     * Serienumero
     */
    serieNumero: string;
    tipoComprobante: Catalog1;
    valorVenta: ComprobanteValorVenta;
};

/**
 * ComprobanteImpuestos
 *
 * Impuestos del comprobante resumido.
 */
export type ComprobanteImpuestos = {
    /**
     * Icb
     */
    icb?: number | string | null;
    /**
     * Igv
     */
    igv: number | string;
};

/**
 * ComprobanteValorVenta
 *
 * Valores de venta del comprobante resumido.
 */
export type ComprobanteValorVenta = {
    /**
     * Exonerado
     */
    exonerado?: number | string | null;
    /**
     * Gravado
     */
    gravado?: number | string | null;
    /**
     * Importetotal
     */
    importeTotal: number | string;
    /**
     * Inafecto
     */
    inafecto?: number | string | null;
};

/**
 * CreditNote
 *
 * Nota de Crédito Electrónica - Tipo 07.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Serie: debe iniciar con B/C o F/E según tipo de documento afectado
 * - Debe referenciar el comprobante afectado
 */
export type CreditNote = {
    cliente: Cliente;
    /**
     * Comprobanteafectadoserienumero
     */
    comprobanteAfectadoSerieNumero: string;
    /**
     * Detalles
     */
    detalles: Array<DocumentoVentaDetalle>;
    /**
     * Fechaemision
     */
    fechaEmision?: string | null;
    /**
     * Igvtotal
     */
    igvTotal?: number | string | null;
    /**
     * Importetotal
     */
    importeTotal?: number | string | null;
    moneda?: Catalog2;
    /**
     * Numero
     */
    numero: number;
    proveedor: Proveedor;
    /**
     * Serie
     *
     * Serie de nota de crédito
     */
    serie: string;
    /**
     * Sustentodescripcion
     */
    sustentoDescripcion: string;
    /**
     * Valorventatotal
     */
    valorVentaTotal?: number | string | null;
};

/**
 * DebitNote
 *
 * Nota de Débito Electrónica - Tipo 08.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Serie: debe iniciar con B/C o F/E según tipo de documento afectado
 * - Debe referenciar el comprobante afectado
 */
export type DebitNote = {
    cliente: Cliente;
    /**
     * Comprobanteafectadoserienumero
     */
    comprobanteAfectadoSerieNumero: string;
    /**
     * Detalles
     */
    detalles: Array<DocumentoVentaDetalle>;
    /**
     * Fechaemision
     */
    fechaEmision?: string | null;
    /**
     * Igvtotal
     */
    igvTotal?: number | string | null;
    /**
     * Importetotal
     */
    importeTotal?: number | string | null;
    moneda?: Catalog2;
    /**
     * Numero
     */
    numero: number;
    proveedor: Proveedor;
    /**
     * Serie
     *
     * Serie de nota de débito
     */
    serie: string;
    /**
     * Sustentodescripcion
     */
    sustentoDescripcion: string;
    /**
     * Valorventatotal
     */
    valorVentaTotal?: number | string | null;
};

/**
 * DocumentoVentaDetalle
 *
 * Línea de detalle de un documento de venta.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Descripción del bien o servicio
 * - Cantidad y unidad de medida (Catálogo N.° 03)
 * - Valor unitario (sin IGV)
 * - Tipo de afectación del IGV (Catálogo N.° 07)
 */
export type DocumentoVentaDetalle = {
    /**
     * Cantidad
     */
    cantidad: number | string;
    /**
     * Descripcion
     */
    descripcion: string;
    /**
     * Igv
     */
    igv?: number | string | null;
    /**
     * Precio
     */
    precio: number | string;
    /**
     * Precioventa
     */
    precioVenta?: number | string | null;
    tipoAfectacionIGV?: Catalog7;
    /**
     * Unidadmedida
     */
    unidadMedida?: string;
    /**
     * Valorventa
     */
    valorVenta?: number | string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Invoice
 *
 * Factura Electrónica - Tipo 01.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Serie: debe iniciar con F (factura) o B (boleta)
 * - Número: correlativo
 * - Tipo de operación: Catálogo N.° 51, default 0101 (Venta interna)
 */
export type Invoice = {
    cliente: Cliente;
    /**
     * Detalles
     */
    detalles: Array<DocumentoVentaDetalle>;
    /**
     * Fechaemision
     */
    fechaEmision?: string | null;
    /**
     * Igvtotal
     */
    igvTotal?: number | string | null;
    /**
     * Importetotal
     */
    importeTotal?: number | string | null;
    moneda?: Catalog2;
    /**
     * Numero
     */
    numero: number;
    proveedor: Proveedor;
    /**
     * Serie
     *
     * Serie de factura (F001) o boleta (B001)
     */
    serie: string;
    tipoOperacion?: Catalog51;
    /**
     * Valorventatotal
     */
    valorVentaTotal?: number | string | null;
};

/**
 * PercepcionRetencionOperacion
 *
 * Operación de percepción.
 */
export type PercepcionRetencionOperacion = {
    comprobante: OpenublModelsPerceptionComprobanteAfectado;
    /**
     * Fechaoperacion
     */
    fechaOperacion: string;
    /**
     * Importeoperacion
     */
    importeOperacion: number | string;
    /**
     * Numerooperacion
     */
    numeroOperacion: number;
};

/**
 * Perception
 *
 * Comprobante de Percepción Electrónico - Tipo 40.
 *
 * RS N° 274-2015/SUNAT, Anexo 1:
 * - Serie: P### (P001, P002, etc.)
 * - Régimen: Catálogo N.° 22
 */
export type Perception = {
    cliente: Cliente;
    /**
     * Fechaemision
     */
    fechaEmision: string;
    /**
     * Importetotalcobrado
     */
    importeTotalCobrado: number | string;
    /**
     * Importetotalpercibido
     */
    importeTotalPercibido: number | string;
    /**
     * Numero
     */
    numero: number;
    /**
     * Operaciones
     */
    operaciones: Array<PercepcionRetencionOperacion>;
    proveedor: Proveedor;
    /**
     * Serie
     *
     * Serie de percepción (P###)
     */
    serie: string;
    tipoRegimen: Catalog22;
    /**
     * Tiporegimenporcentaje
     */
    tipoRegimenPorcentaje: number | string;
};

/**
 * Proveedor
 *
 * Datos del emisor del comprobante.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - RUC del emisor: 11 dígitos numéricos (Catálogo N.° 06, valor 6)
 * - Razón social: obligatoria
 */
export type Proveedor = {
    address?: Address | null;
    /**
     * Nombrecomercial
     */
    nombreComercial?: string | null;
    /**
     * Razonsocial
     */
    razonSocial: string;
    /**
     * Ruc
     *
     * RUC del emisor - 11 dígitos numéricos
     */
    ruc: string;
};

/**
 * Retention
 *
 * Comprobante de Retención Electrónico - Tipo 20.
 *
 * RS N° 274-2015/SUNAT, Anexo 1:
 * - Serie: R### (R001, R002, etc.)
 * - Régimen: Catálogo N.° 23
 */
export type Retention = {
    /**
     * Importetotalpagado
     */
    importeTotalPagado: number | string;
    /**
     * Importetotalretenido
     */
    importeTotalRetenido: number | string;
    /**
     * Operaciones
     */
    operaciones: Array<PercepcionRetencionOperacion>;
    /**
     * Serie
     *
     * Serie de retención (R###)
     */
    serie: string;
    tipoRegimen: Catalog23;
    /**
     * Tiporegimenporcentaje
     */
    tipoRegimenPorcentaje: number | string;
};

/**
 * SignedXmlResponse
 *
 * Response containing signed XML document.
 */
export type SignedXmlResponse = {
    /**
     * Signed Xml
     */
    signed_xml: string;
};

/**
 * SummaryDocuments
 *
 * Resumen Diario - RC.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Identificador: RC-YYYYMMDD-NNNN
 * - Fecha de emisión de los comprobantes resumidos
 */
export type SummaryDocuments = {
    /**
     * Comprobantes
     */
    comprobantes: Array<SummaryDocumentsItem>;
    /**
     * Fechaemisioncomprobantes
     */
    fechaEmisionComprobantes: string;
    /**
     * Numero
     */
    numero: number;
    proveedor: Proveedor;
};

/**
 * SummaryDocumentsItem
 *
 * Item del resumen diario.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Tipo de operación: Catálogo N.° 19 (ADICIONAR, MODIFICAR, ANULADO)
 */
export type SummaryDocumentsItem = {
    comprobante: Comprobante;
    tipoOperacion: Catalog19;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VoidedDocuments
 *
 * Comunicación de Baja - RA.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Identificador: RA-YYYYMMDD-NNNN
 * - Fecha de emisión de los comprobantes que se dan de baja
 */
export type VoidedDocuments = {
    /**
     * Comprobantes
     */
    comprobantes: Array<VoidedDocumentsItem>;
    /**
     * Fechaemision
     */
    fechaEmision?: string | null;
    /**
     * Fechaemisioncomprobantes
     */
    fechaEmisionComprobantes: string;
    /**
     * Numero
     */
    numero: number;
    proveedor: Proveedor;
};

/**
 * VoidedDocumentsItem
 *
 * Item de comunicación de baja.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Tipo de comprobante: Catálogo N.° 01
 * - Serie y número del comprobante a dar de baja
 */
export type VoidedDocumentsItem = {
    /**
     * Descripcionsustento
     */
    descripcionSustento: string;
    /**
     * Numero
     */
    numero: number;
    /**
     * Serie
     */
    serie: string;
    tipoComprobante: Catalog1;
};

/**
 * XmlResponse
 *
 * Response containing generated XML document.
 */
export type XmlResponse = {
    /**
     * Xml
     */
    xml: string;
};

/**
 * ComprobanteAfectado
 *
 * Comprobante afectado por la percepción.
 */
export type OpenublModelsPerceptionComprobanteAfectado = {
    /**
     * Fechaemision
     */
    fechaEmision: string;
    /**
     * Importetotal
     */
    importeTotal: number | string;
    moneda: Catalog2;
    /**
     * Serienumero
     */
    serieNumero: string;
    /**
     * Tipocomprobante
     */
    tipoComprobante: string;
};

/**
 * ComprobanteAfectado
 *
 * Comprobante afectado para notas.
 */
export type OpenublModelsSummaryComprobanteAfectado = {
    /**
     * Fechaemision
     */
    fechaEmision: string;
    /**
     * Importetotal
     */
    importeTotal: number | string;
    /**
     * Moneda
     */
    moneda: string;
    /**
     * Serienumero
     */
    serieNumero: string;
    tipoComprobante: Catalog1;
};

export type CreateCreditNoteData = {
    body: CreditNote;
    path?: never;
    query?: {
        /**
         * Validate
         */
        validate?: boolean;
    };
    url: '/api/v1/credit-note/create';
};

export type CreateCreditNoteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCreditNoteError = CreateCreditNoteErrors[keyof CreateCreditNoteErrors];

export type CreateCreditNoteResponses = {
    /**
     * Successful Response
     */
    200: XmlResponse;
};

export type CreateCreditNoteResponse = CreateCreditNoteResponses[keyof CreateCreditNoteResponses];

export type CreateDebitNoteData = {
    body: DebitNote;
    path?: never;
    query?: {
        /**
         * Validate
         */
        validate?: boolean;
    };
    url: '/api/v1/debit-note/create';
};

export type CreateDebitNoteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDebitNoteError = CreateDebitNoteErrors[keyof CreateDebitNoteErrors];

export type CreateDebitNoteResponses = {
    /**
     * Successful Response
     */
    200: XmlResponse;
};

export type CreateDebitNoteResponse = CreateDebitNoteResponses[keyof CreateDebitNoteResponses];

export type CreateInvoiceData = {
    body: Invoice;
    path?: never;
    query?: {
        /**
         * Validate
         */
        validate?: boolean;
    };
    url: '/api/v1/invoice/create';
};

export type CreateInvoiceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateInvoiceError = CreateInvoiceErrors[keyof CreateInvoiceErrors];

export type CreateInvoiceResponses = {
    /**
     * Successful Response
     */
    200: XmlResponse;
};

export type CreateInvoiceResponse = CreateInvoiceResponses[keyof CreateInvoiceResponses];

export type CreatePerceptionData = {
    body: Perception;
    path?: never;
    query?: {
        /**
         * Validate
         */
        validate?: boolean;
    };
    url: '/api/v1/perception/create';
};

export type CreatePerceptionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePerceptionError = CreatePerceptionErrors[keyof CreatePerceptionErrors];

export type CreatePerceptionResponses = {
    /**
     * Successful Response
     */
    200: XmlResponse;
};

export type CreatePerceptionResponse = CreatePerceptionResponses[keyof CreatePerceptionResponses];

export type CreateRetentionData = {
    body: Retention;
    path?: never;
    query?: {
        /**
         * Validate
         */
        validate?: boolean;
    };
    url: '/api/v1/retention/create';
};

export type CreateRetentionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRetentionError = CreateRetentionErrors[keyof CreateRetentionErrors];

export type CreateRetentionResponses = {
    /**
     * Successful Response
     */
    200: XmlResponse;
};

export type CreateRetentionResponse = CreateRetentionResponses[keyof CreateRetentionResponses];

export type SignXmlData = {
    /**
     * Payload
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/v1/sign';
};

export type SignXmlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SignXmlError = SignXmlErrors[keyof SignXmlErrors];

export type SignXmlResponses = {
    /**
     * Successful Response
     */
    200: SignedXmlResponse;
};

export type SignXmlResponse = SignXmlResponses[keyof SignXmlResponses];

export type CreateSummaryDocumentsData = {
    body: SummaryDocuments;
    path?: never;
    query?: {
        /**
         * Validate
         */
        validate?: boolean;
    };
    url: '/api/v1/summary-documents/create';
};

export type CreateSummaryDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSummaryDocumentsError = CreateSummaryDocumentsErrors[keyof CreateSummaryDocumentsErrors];

export type CreateSummaryDocumentsResponses = {
    /**
     * Successful Response
     */
    200: XmlResponse;
};

export type CreateSummaryDocumentsResponse = CreateSummaryDocumentsResponses[keyof CreateSummaryDocumentsResponses];

export type GetVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/version';
};

export type GetVersionResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateVoidedDocumentsData = {
    body: VoidedDocuments;
    path?: never;
    query?: {
        /**
         * Validate
         */
        validate?: boolean;
    };
    url: '/api/v1/voided-documents/create';
};

export type CreateVoidedDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateVoidedDocumentsError = CreateVoidedDocumentsErrors[keyof CreateVoidedDocumentsErrors];

export type CreateVoidedDocumentsResponses = {
    /**
     * Successful Response
     */
    200: XmlResponse;
};

export type CreateVoidedDocumentsResponse = CreateVoidedDocumentsResponses[keyof CreateVoidedDocumentsResponses];
