// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * Address
 *
 * Dirección según esquema UBL 2.1 de SUNAT.
 */
export const zAddress = z.object({
    codigoPais: z.string().optional().default('PE'),
    departamento: z.string().nullish(),
    direccion: z.string().nullish(),
    distrito: z.string().nullish(),
    provincia: z.string().nullish(),
    ubigeo: z.string().nullish(),
    urbanizacion: z.string().nullish()
});

/**
 * Catalog1
 *
 * Tipo de Comprobante - Catálogo N.° 01
 */
export const zCatalog1 = z.enum([
    '01',
    '03',
    '07',
    '08',
    '09',
    '20',
    '40'
]);

/**
 * Catalog19
 *
 * Tipo de Operación - Resumen Diario - Catálogo N.° 19
 */
export const zCatalog19 = z.enum([
    '1',
    '2',
    '3'
]);

/**
 * Catalog2
 *
 * Tipo de Moneda - Catálogo N.° 02
 */
export const zCatalog2 = z.enum([
    'PEN',
    'USD',
    'EUR'
]);

/**
 * Catalog22
 *
 * Régimen de Percepción - Catálogo N.° 22
 */
export const zCatalog22 = z.enum([
    '01',
    '02',
    '03'
]);

/**
 * Catalog23
 *
 * Régimen de Retención - Catálogo N.° 23
 */
export const zCatalog23 = z.enum([
    '01',
    '02',
    '03'
]);

/**
 * Catalog51
 *
 * Tipo de Operación - Catálogo N.° 51
 */
export const zCatalog51 = z.enum([
    '0101',
    '0102',
    '0103',
    '0104',
    '0105',
    '0106',
    '0107',
    '0108',
    '0110',
    '0200',
    '0201',
    '0202',
    '0203',
    '0204',
    '0205',
    '0206',
    '0207'
]);

/**
 * Catalog6
 *
 * Tipo de Documento de Identidad - Catálogo N.° 06
 */
export const zCatalog6 = z.enum([
    '0',
    '1',
    '4',
    '6',
    '7'
]);

/**
 * Catalog7
 *
 * Tipo de Afectación del IGV - Catálogo N.° 07
 */
export const zCatalog7 = z.enum([
    '10',
    '20',
    '30'
]);

/**
 * Cliente
 *
 * Datos del adquirente o usuario.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Tipo de documento: Catálogo N.° 06
 * - Número de documento: según tipo
 */
export const zCliente = z.object({
    nombre: z.string(),
    numeroDocumentoIdentidad: z.string().min(1).regex(/^\w+$/),
    tipoDocumentoIdentidad: zCatalog6
});

/**
 * ComprobanteImpuestos
 *
 * Impuestos del comprobante resumido.
 */
export const zComprobanteImpuestos = z.object({
    icb: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    igv: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ])
});

/**
 * ComprobanteValorVenta
 *
 * Valores de venta del comprobante resumido.
 */
export const zComprobanteValorVenta = z.object({
    exonerado: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    gravado: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    importeTotal: z.union([
        z.number().gte(0),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    inafecto: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish()
});

/**
 * DocumentoVentaDetalle
 *
 * Línea de detalle de un documento de venta.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Descripción del bien o servicio
 * - Cantidad y unidad de medida (Catálogo N.° 03)
 * - Valor unitario (sin IGV)
 * - Tipo de afectación del IGV (Catálogo N.° 07)
 */
export const zDocumentoVentaDetalle = z.object({
    cantidad: z.union([
        z.number().gt(0),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    descripcion: z.string(),
    igv: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    precio: z.union([
        z.number().gte(0),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    precioVenta: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    tipoAfectacionIGV: zCatalog7.optional().default('10'),
    unidadMedida: z.string().optional().default('NIU'),
    valorVenta: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish()
});

/**
 * Proveedor
 *
 * Datos del emisor del comprobante.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - RUC del emisor: 11 dígitos numéricos (Catálogo N.° 06, valor 6)
 * - Razón social: obligatoria
 */
export const zProveedor = z.object({
    address: zAddress.nullish(),
    nombreComercial: z.string().nullish(),
    razonSocial: z.string(),
    ruc: z.string().length(11).regex(/^\d{11}$/)
});

/**
 * CreditNote
 *
 * Nota de Crédito Electrónica - Tipo 07.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Serie: debe iniciar con B/C o F/E según tipo de documento afectado
 * - Debe referenciar el comprobante afectado
 */
export const zCreditNote = z.object({
    cliente: zCliente,
    comprobanteAfectadoSerieNumero: z.string(),
    detalles: z.array(zDocumentoVentaDetalle),
    fechaEmision: z.string().date().nullish(),
    igvTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    importeTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    moneda: zCatalog2.optional().default('PEN'),
    numero: z.number().int().gte(1),
    proveedor: zProveedor,
    serie: z.string().regex(/^[BCbc][A-Za-z0-9]{2,3}$/),
    sustentoDescripcion: z.string(),
    valorVentaTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish()
});

/**
 * DebitNote
 *
 * Nota de Débito Electrónica - Tipo 08.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Serie: debe iniciar con B/C o F/E según tipo de documento afectado
 * - Debe referenciar el comprobante afectado
 */
export const zDebitNote = z.object({
    cliente: zCliente,
    comprobanteAfectadoSerieNumero: z.string(),
    detalles: z.array(zDocumentoVentaDetalle),
    fechaEmision: z.string().date().nullish(),
    igvTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    importeTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    moneda: zCatalog2.optional().default('PEN'),
    numero: z.number().int().gte(1),
    proveedor: zProveedor,
    serie: z.string().regex(/^[BCbc][A-Za-z0-9]{2,3}$/),
    sustentoDescripcion: z.string(),
    valorVentaTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish()
});

/**
 * Invoice
 *
 * Factura Electrónica - Tipo 01.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Serie: debe iniciar con F (factura) o B (boleta)
 * - Número: correlativo
 * - Tipo de operación: Catálogo N.° 51, default 0101 (Venta interna)
 */
export const zInvoice = z.object({
    cliente: zCliente,
    detalles: z.array(zDocumentoVentaDetalle),
    fechaEmision: z.string().date().nullish(),
    igvTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    importeTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    moneda: zCatalog2.optional().default('PEN'),
    numero: z.number().int().gte(1),
    proveedor: zProveedor,
    serie: z.string().regex(/^[FBfb][A-Za-z0-9]{2,3}$/),
    tipoOperacion: zCatalog51.optional().default('0101'),
    valorVentaTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish()
});

/**
 * SignedXmlResponse
 *
 * Response containing signed XML document.
 */
export const zSignedXmlResponse = z.object({
    signed_xml: z.string()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    ctx: z.record(z.unknown()).optional(),
    input: z.unknown().optional(),
    loc: z.array(z.union([z.string(), z.number().int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * VoidedDocumentsItem
 *
 * Item de comunicación de baja.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Tipo de comprobante: Catálogo N.° 01
 * - Serie y número del comprobante a dar de baja
 */
export const zVoidedDocumentsItem = z.object({
    descripcionSustento: z.string(),
    numero: z.number().int().gte(1),
    serie: z.string(),
    tipoComprobante: zCatalog1
});

/**
 * VoidedDocuments
 *
 * Comunicación de Baja - RA.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Identificador: RA-YYYYMMDD-NNNN
 * - Fecha de emisión de los comprobantes que se dan de baja
 */
export const zVoidedDocuments = z.object({
    comprobantes: z.array(zVoidedDocumentsItem),
    fechaEmision: z.string().date().nullish(),
    fechaEmisionComprobantes: z.string().date(),
    numero: z.number().int().gte(1),
    proveedor: zProveedor
});

/**
 * XmlResponse
 *
 * Response containing generated XML document.
 */
export const zXmlResponse = z.object({
    xml: z.string()
});

/**
 * ComprobanteAfectado
 *
 * Comprobante afectado por la percepción.
 */
export const zOpenublModelsPerceptionComprobanteAfectado = z.object({
    fechaEmision: z.string().date(),
    importeTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    moneda: zCatalog2,
    serieNumero: z.string(),
    tipoComprobante: z.string()
});

/**
 * PercepcionRetencionOperacion
 *
 * Operación de percepción.
 */
export const zPercepcionRetencionOperacion = z.object({
    comprobante: zOpenublModelsPerceptionComprobanteAfectado,
    fechaOperacion: z.string().date(),
    importeOperacion: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    numeroOperacion: z.number().int()
});

/**
 * Perception
 *
 * Comprobante de Percepción Electrónico - Tipo 40.
 *
 * RS N° 274-2015/SUNAT, Anexo 1:
 * - Serie: P### (P001, P002, etc.)
 * - Régimen: Catálogo N.° 22
 */
export const zPerception = z.object({
    cliente: zCliente,
    fechaEmision: z.string().date(),
    importeTotalCobrado: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    importeTotalPercibido: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    numero: z.number().int().gte(1),
    operaciones: z.array(zPercepcionRetencionOperacion),
    proveedor: zProveedor,
    serie: z.string().regex(/^P\d{3}$/),
    tipoRegimen: zCatalog22,
    tipoRegimenPorcentaje: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ])
});

/**
 * Retention
 *
 * Comprobante de Retención Electrónico - Tipo 20.
 *
 * RS N° 274-2015/SUNAT, Anexo 1:
 * - Serie: R### (R001, R002, etc.)
 * - Régimen: Catálogo N.° 23
 */
export const zRetention = z.object({
    importeTotalPagado: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    importeTotalRetenido: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    operaciones: z.array(zPercepcionRetencionOperacion),
    serie: z.string().regex(/^R\d{3}$/),
    tipoRegimen: zCatalog23,
    tipoRegimenPorcentaje: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ])
});

/**
 * ComprobanteAfectado
 *
 * Comprobante afectado para notas.
 */
export const zOpenublModelsSummaryComprobanteAfectado = z.object({
    fechaEmision: z.string().date(),
    importeTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    moneda: z.string(),
    serieNumero: z.string(),
    tipoComprobante: zCatalog1
});

/**
 * Comprobante
 *
 * Comprobante dentro del resumen diario.
 */
export const zComprobante = z.object({
    cliente: zCliente,
    comprobanteAfectado: zOpenublModelsSummaryComprobanteAfectado.nullish(),
    impuestos: zComprobanteImpuestos,
    serieNumero: z.string(),
    tipoComprobante: zCatalog1,
    valorVenta: zComprobanteValorVenta
});

/**
 * SummaryDocumentsItem
 *
 * Item del resumen diario.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Tipo de operación: Catálogo N.° 19 (ADICIONAR, MODIFICAR, ANULADO)
 */
export const zSummaryDocumentsItem = z.object({
    comprobante: zComprobante,
    tipoOperacion: zCatalog19
});

/**
 * SummaryDocuments
 *
 * Resumen Diario - RC.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Identificador: RC-YYYYMMDD-NNNN
 * - Fecha de emisión de los comprobantes resumidos
 */
export const zSummaryDocuments = z.object({
    comprobantes: z.array(zSummaryDocumentsItem),
    fechaEmisionComprobantes: z.string().date(),
    numero: z.number().int(),
    proveedor: zProveedor
});

export const zCreateCreditNoteApiV1CreditNoteCreatePostBody = zCreditNote;

export const zCreateCreditNoteApiV1CreditNoteCreatePostQuery = z.object({
    validate: z.boolean().optional().default(true)
});

/**
 * Successful Response
 */
export const zCreateCreditNoteApiV1CreditNoteCreatePostResponse = zXmlResponse;

export const zCreateDebitNoteApiV1DebitNoteCreatePostBody = zDebitNote;

export const zCreateDebitNoteApiV1DebitNoteCreatePostQuery = z.object({
    validate: z.boolean().optional().default(true)
});

/**
 * Successful Response
 */
export const zCreateDebitNoteApiV1DebitNoteCreatePostResponse = zXmlResponse;

export const zCreateInvoiceApiV1InvoiceCreatePostBody = zInvoice;

export const zCreateInvoiceApiV1InvoiceCreatePostQuery = z.object({
    validate: z.boolean().optional().default(true)
});

/**
 * Successful Response
 */
export const zCreateInvoiceApiV1InvoiceCreatePostResponse = zXmlResponse;

export const zCreatePerceptionApiV1PerceptionCreatePostBody = zPerception;

export const zCreatePerceptionApiV1PerceptionCreatePostQuery = z.object({
    validate: z.boolean().optional().default(true)
});

/**
 * Successful Response
 */
export const zCreatePerceptionApiV1PerceptionCreatePostResponse = zXmlResponse;

export const zCreateRetentionApiV1RetentionCreatePostBody = zRetention;

export const zCreateRetentionApiV1RetentionCreatePostQuery = z.object({
    validate: z.boolean().optional().default(true)
});

/**
 * Successful Response
 */
export const zCreateRetentionApiV1RetentionCreatePostResponse = zXmlResponse;

/**
 * Payload
 */
export const zSignXmlApiV1SignPostBody = z.record(z.unknown());

/**
 * Successful Response
 */
export const zSignXmlApiV1SignPostResponse = zSignedXmlResponse;

export const zCreateSummaryDocumentsApiV1SummaryDocumentsCreatePostBody = zSummaryDocuments;

export const zCreateSummaryDocumentsApiV1SummaryDocumentsCreatePostQuery = z.object({
    validate: z.boolean().optional().default(true)
});

/**
 * Successful Response
 */
export const zCreateSummaryDocumentsApiV1SummaryDocumentsCreatePostResponse = zXmlResponse;

export const zCreateVoidedDocumentsApiV1VoidedDocumentsCreatePostBody = zVoidedDocuments;

export const zCreateVoidedDocumentsApiV1VoidedDocumentsCreatePostQuery = z.object({
    validate: z.boolean().optional().default(true)
});

/**
 * Successful Response
 */
export const zCreateVoidedDocumentsApiV1VoidedDocumentsCreatePostResponse = zXmlResponse;
