// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * Address
 *
 * Dirección según esquema UBL 2.1 de SUNAT.
 */
export const zAddress = z.object({
    codigoPais: z.string().optional().default('PE'),
    departamento: z.string().nullish(),
    direccion: z.string().nullish(),
    distrito: z.string().nullish(),
    provincia: z.string().nullish(),
    ubigeo: z.string().nullish(),
    urbanizacion: z.string().nullish()
});

/**
 * Catalog1
 *
 * Tipo de Comprobante - Catálogo N.° 01
 */
export const zCatalog1 = z.enum([
    '01',
    '03',
    '07',
    '08',
    '09',
    '20',
    '40'
]);

/**
 * Catalog19
 *
 * Tipo de Operación - Resumen Diario - Catálogo N.° 19
 */
export const zCatalog19 = z.enum([
    '1',
    '2',
    '3'
]);

/**
 * Catalog2
 *
 * Tipo de Moneda - Catálogo N.° 02
 */
export const zCatalog2 = z.enum([
    'PEN',
    'USD',
    'EUR'
]);

/**
 * Catalog22
 *
 * Régimen de Percepción - Catálogo N.° 22
 */
export const zCatalog22 = z.enum([
    '01',
    '02',
    '03'
]);

/**
 * Catalog23
 *
 * Régimen de Retención - Catálogo N.° 23
 */
export const zCatalog23 = z.enum([
    '01',
    '02',
    '03'
]);

/**
 * Catalog51
 *
 * Tipo de Operación - Catálogo N.° 51
 */
export const zCatalog51 = z.enum([
    '0101',
    '0102',
    '0103',
    '0104',
    '0105',
    '0106',
    '0107',
    '0108',
    '0110',
    '0200',
    '0201',
    '0202',
    '0203',
    '0204',
    '0205',
    '0206',
    '0207'
]);

/**
 * Catalog6
 *
 * Tipo de Documento de Identidad - Catálogo N.° 06
 */
export const zCatalog6 = z.enum([
    '0',
    '1',
    '4',
    '6',
    '7'
]);

/**
 * Catalog7
 *
 * Tipo de Afectación del IGV - Catálogo N.° 07
 */
export const zCatalog7 = z.enum([
    '10',
    '20',
    '30'
]);

/**
 * Cliente
 *
 * Datos del adquirente o usuario.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Tipo de documento: Catálogo N.° 06
 * - Número de documento: según tipo
 */
export const zCliente = z.object({
    nombre: z.string(),
    numeroDocumentoIdentidad: z.string().min(1).regex(/^\w+$/),
    tipoDocumentoIdentidad: zCatalog6
});

/**
 * ComprobanteImpuestos
 *
 * Impuestos del comprobante resumido.
 */
export const zComprobanteImpuestos = z.object({
    icb: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    igv: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ])
});

/**
 * ComprobanteValorVenta
 *
 * Valores de venta del comprobante resumido.
 */
export const zComprobanteValorVenta = z.object({
    exonerado: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    gravado: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    importeTotal: z.union([
        z.number().gte(0),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    inafecto: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish()
});

/**
 * CreateResponse
 *
 * Respuesta unificada de los endpoints /create.
 */
export const zCreateResponse = z.object({
    errors: z.array(z.record(z.unknown())).nullish(),
    firmado: z.boolean(),
    valid: z.boolean().nullish(),
    validado_sunat: z.boolean(),
    xml: z.string()
});

/**
 * Credentials
 *
 * Credenciales para firma digital.
 */
export const zCredentials = z.object({
    cert_pem: z.string().nullish(),
    key_pem: z.string().nullish(),
    pfx_base64: z.string().nullish(),
    pfx_password: z.string().nullish()
});

/**
 * DocumentoVentaDetalle
 *
 * Línea de detalle de un documento de venta.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Descripción del bien o servicio
 * - Cantidad y unidad de medida (Catálogo N.° 03)
 * - Valor unitario (sin IGV)
 * - Tipo de afectación del IGV (Catálogo N.° 07)
 */
export const zDocumentoVentaDetalle = z.object({
    cantidad: z.union([
        z.number().gt(0),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    descripcion: z.string(),
    igv: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    precio: z.union([
        z.number().gte(0),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    precioVenta: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    tipoAfectacionIGV: zCatalog7.optional().default('10'),
    unidadMedida: z.string().optional().default('NIU'),
    valorVenta: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish()
});

/**
 * Proveedor
 *
 * Datos del emisor del comprobante.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - RUC del emisor: 11 dígitos numéricos (Catálogo N.° 06, valor 6)
 * - Razón social: obligatoria
 */
export const zProveedor = z.object({
    address: zAddress.nullish(),
    nombreComercial: z.string().nullish(),
    razonSocial: z.string(),
    ruc: z.string().length(11).regex(/^\d{11}$/)
});

/**
 * CreditNote
 *
 * Nota de Crédito Electrónica - Tipo 07.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Serie: debe iniciar con B/C o F/E según tipo de documento afectado
 * - Debe referenciar el comprobante afectado
 */
export const zCreditNote = z.object({
    cliente: zCliente,
    comprobanteAfectadoSerieNumero: z.string(),
    detalles: z.array(zDocumentoVentaDetalle),
    fechaEmision: z.string().date().nullish(),
    igvTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    importeTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    moneda: zCatalog2.optional().default('PEN'),
    numero: z.number().int().gte(1),
    proveedor: zProveedor,
    serie: z.string(),
    sustentoDescripcion: z.string(),
    valorVentaTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish()
});

/**
 * CreditNoteCreateRequest
 *
 * Request para crear una nota de crédito.
 */
export const zCreditNoteCreateRequest = z.object({
    credenciales: zCredentials.nullish(),
    documento: zCreditNote,
    firmar: z.boolean().optional().default(false),
    signature_id: z.string().optional().default('SignSUNAT'),
    validar_sunat: z.boolean().optional().default(true)
});

/**
 * DebitNote
 *
 * Nota de Débito Electrónica - Tipo 08.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Serie: debe iniciar con B/C o F/E según tipo de documento afectado
 * - Debe referenciar el comprobante afectado
 */
export const zDebitNote = z.object({
    cliente: zCliente,
    comprobanteAfectadoSerieNumero: z.string(),
    detalles: z.array(zDocumentoVentaDetalle),
    fechaEmision: z.string().date().nullish(),
    igvTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    importeTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    moneda: zCatalog2.optional().default('PEN'),
    numero: z.number().int().gte(1),
    proveedor: zProveedor,
    serie: z.string(),
    sustentoDescripcion: z.string(),
    valorVentaTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish()
});

/**
 * DebitNoteCreateRequest
 *
 * Request para crear una nota de débito.
 */
export const zDebitNoteCreateRequest = z.object({
    credenciales: zCredentials.nullish(),
    documento: zDebitNote,
    firmar: z.boolean().optional().default(false),
    signature_id: z.string().optional().default('SignSUNAT'),
    validar_sunat: z.boolean().optional().default(true)
});

/**
 * Invoice
 *
 * Factura Electrónica - Tipo 01.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Serie: debe iniciar con F (factura) o B (boleta)
 * - Número: correlativo
 * - Tipo de operación: Catálogo N.° 51, default 0101 (Venta interna)
 */
export const zInvoice = z.object({
    cliente: zCliente,
    detalles: z.array(zDocumentoVentaDetalle),
    fechaEmision: z.string().date().nullish(),
    igvTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    importeTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    moneda: zCatalog2.optional().default('PEN'),
    numero: z.number().int().gte(1),
    proveedor: zProveedor,
    serie: z.string().min(1),
    tipoOperacion: zCatalog51.optional().default('0101'),
    valorVentaTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish()
});

/**
 * InvoiceCreateRequest
 *
 * Request para crear una factura.
 */
export const zInvoiceCreateRequest = z.object({
    credenciales: zCredentials.nullish(),
    documento: zInvoice,
    firmar: z.boolean().optional().default(false),
    signature_id: z.string().optional().default('SignSUNAT'),
    validar_sunat: z.boolean().optional().default(true)
});

/**
 * SignedXmlResponse
 *
 * Response containing signed XML document.
 */
export const zSignedXmlResponse = z.object({
    signed_xml: z.string()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    ctx: z.record(z.unknown()).optional(),
    input: z.unknown().optional(),
    loc: z.array(z.union([z.string(), z.number().int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * VoidedDocumentsItem
 *
 * Item de comunicación de baja.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Tipo de comprobante: Catálogo N.° 01
 * - Serie y número del comprobante a dar de baja
 */
export const zVoidedDocumentsItem = z.object({
    descripcionSustento: z.string(),
    numero: z.number().int().gte(1),
    serie: z.string(),
    tipoComprobante: zCatalog1
});

/**
 * VoidedDocuments
 *
 * Comunicación de Baja - RA.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Identificador: RA-YYYYMMDD-NNNN
 * - Fecha de emisión de los comprobantes que se dan de baja
 */
export const zVoidedDocuments = z.object({
    comprobantes: z.array(zVoidedDocumentsItem),
    fechaEmision: z.string().date().nullish(),
    fechaEmisionComprobantes: z.string().date(),
    numero: z.number().int().gte(1),
    proveedor: zProveedor
});

/**
 * VoidedDocumentsCreateRequest
 *
 * Request para crear una comunicación de baja.
 */
export const zVoidedDocumentsCreateRequest = z.object({
    credenciales: zCredentials.nullish(),
    documento: zVoidedDocuments,
    firmar: z.boolean().optional().default(false),
    signature_id: z.string().optional().default('SignSUNAT'),
    validar_sunat: z.boolean().optional().default(true)
});

/**
 * ComprobanteAfectado
 *
 * Comprobante afectado por la percepción.
 */
export const zOpenublModelsPerceptionComprobanteAfectado = z.object({
    fechaEmision: z.string().date(),
    importeTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    moneda: zCatalog2,
    serieNumero: z.string(),
    tipoComprobante: z.string()
});

/**
 * PercepcionRetencionOperacion
 *
 * Operación de percepción.
 */
export const zPercepcionRetencionOperacion = z.object({
    comprobante: zOpenublModelsPerceptionComprobanteAfectado,
    fechaOperacion: z.string().date(),
    importeOperacion: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    numeroOperacion: z.number().int()
});

/**
 * Perception
 *
 * Comprobante de Percepción Electrónico - Tipo 40.
 *
 * RS N° 274-2015/SUNAT, Anexo 1:
 * - Serie: P### (P001, P002, etc.)
 * - Régimen: Catálogo N.° 22
 */
export const zPerception = z.object({
    cliente: zCliente,
    fechaEmision: z.string().date(),
    importeTotalCobrado: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    importeTotalPercibido: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    numero: z.number().int().gte(1),
    operaciones: z.array(zPercepcionRetencionOperacion),
    proveedor: zProveedor,
    serie: z.string().regex(/^P\d{3}$/),
    tipoRegimen: zCatalog22,
    tipoRegimenPorcentaje: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ])
});

/**
 * PerceptionCreateRequest
 *
 * Request para crear una percepción.
 */
export const zPerceptionCreateRequest = z.object({
    credenciales: zCredentials.nullish(),
    documento: zPerception,
    firmar: z.boolean().optional().default(false),
    signature_id: z.string().optional().default('SignSUNAT'),
    validar_sunat: z.boolean().optional().default(true)
});

/**
 * Retention
 *
 * Comprobante de Retención Electrónico - Tipo 20.
 *
 * RS N° 274-2015/SUNAT, Anexo 1:
 * - Serie: R### (R001, R002, etc.)
 * - Régimen: Catálogo N.° 23
 */
export const zRetention = z.object({
    cliente: zCliente,
    fechaEmision: z.string().date(),
    importeTotalPagado: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    importeTotalRetenido: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    numero: z.number().int().gte(1),
    operaciones: z.array(zPercepcionRetencionOperacion),
    proveedor: zProveedor,
    serie: z.string().regex(/^R\d{3}$/),
    tipoRegimen: zCatalog23,
    tipoRegimenPorcentaje: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ])
});

/**
 * RetentionCreateRequest
 *
 * Request para crear una retención.
 */
export const zRetentionCreateRequest = z.object({
    credenciales: zCredentials.nullish(),
    documento: zRetention,
    firmar: z.boolean().optional().default(false),
    signature_id: z.string().optional().default('SignSUNAT'),
    validar_sunat: z.boolean().optional().default(true)
});

/**
 * ComprobanteAfectado
 *
 * Comprobante afectado para notas.
 */
export const zOpenublModelsSummaryComprobanteAfectado = z.object({
    fechaEmision: z.string().date(),
    importeTotal: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    moneda: z.string(),
    serieNumero: z.string(),
    tipoComprobante: zCatalog1
});

/**
 * Comprobante
 *
 * Comprobante dentro del resumen diario.
 */
export const zComprobante = z.object({
    cliente: zCliente,
    comprobanteAfectado: zOpenublModelsSummaryComprobanteAfectado.nullish(),
    impuestos: zComprobanteImpuestos,
    serieNumero: z.string(),
    tipoComprobante: zCatalog1,
    valorVenta: zComprobanteValorVenta
});

/**
 * SummaryDocumentsItem
 *
 * Item del resumen diario.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Tipo de operación: Catálogo N.° 19 (ADICIONAR, MODIFICAR, ANULADO)
 */
export const zSummaryDocumentsItem = z.object({
    comprobante: zComprobante,
    tipoOperacion: zCatalog19
});

/**
 * SummaryDocuments
 *
 * Resumen Diario - RC.
 *
 * RS N° 300-2014/SUNAT, Anexo 1:
 * - Identificador: RC-YYYYMMDD-NNNN
 * - Fecha de emisión de los comprobantes resumidos
 */
export const zSummaryDocuments = z.object({
    comprobantes: z.array(zSummaryDocumentsItem),
    fechaEmisionComprobantes: z.string().date(),
    numero: z.number().int(),
    proveedor: zProveedor
});

/**
 * SummaryDocumentsCreateRequest
 *
 * Request para crear un resumen diario.
 */
export const zSummaryDocumentsCreateRequest = z.object({
    credenciales: zCredentials.nullish(),
    documento: zSummaryDocuments,
    firmar: z.boolean().optional().default(false),
    signature_id: z.string().optional().default('SignSUNAT'),
    validar_sunat: z.boolean().optional().default(true)
});

export const zCreateCreditNoteBody = zCreditNoteCreateRequest;

/**
 * Successful Response
 */
export const zCreateCreditNoteResponse = zCreateResponse;

export const zCreateDebitNoteBody = zDebitNoteCreateRequest;

/**
 * Successful Response
 */
export const zCreateDebitNoteResponse = zCreateResponse;

export const zCreateInvoiceBody = zInvoiceCreateRequest;

/**
 * Successful Response
 */
export const zCreateInvoiceResponse = zCreateResponse;

export const zCreatePerceptionBody = zPerceptionCreateRequest;

/**
 * Successful Response
 */
export const zCreatePerceptionResponse = zCreateResponse;

export const zCreateRetentionBody = zRetentionCreateRequest;

/**
 * Successful Response
 */
export const zCreateRetentionResponse = zCreateResponse;

/**
 * Payload
 */
export const zSignXmlBody = z.record(z.unknown());

/**
 * Successful Response
 */
export const zSignXmlResponse = zSignedXmlResponse;

export const zCreateSummaryDocumentsBody = zSummaryDocumentsCreateRequest;

/**
 * Successful Response
 */
export const zCreateSummaryDocumentsResponse = zCreateResponse;

export const zCreateVoidedDocumentsBody = zVoidedDocumentsCreateRequest;

/**
 * Successful Response
 */
export const zCreateVoidedDocumentsResponse = zCreateResponse;
